### ISSUE TITLE
Issue with libsodium.so: undefined symbol: crypto_vrf_ietfdraft03_proofbytes

### ISSUE THREAD

**Issue by billionairepool** [papacarp/pooltool.io#114]
Command

```
python3 leaderLogs.py \
         --pool-id $(cat ${NODE_HOME}/stakepoolid.txt) \
         --sigma ${sigmaValue} \
         --tz America/Los_Angeles \
         --vrf-skey ${NODE_HOME}/vrf.skey
```

outputs with error

```
[INFO]: No epoch provided, using latest known epoch.
Checking leadership log for Epoch 244 [ d Param: 0.26 ]
Traceback (most recent call last):
  File "leaderLogs.py", line 147, in <module>
    slotLeader = isSlotLeader(slot, activeSlotCoeff, sigma, eta0, poolVrfSkey)
  File "leaderLogs.py", line 131, in isSlotLeader
    cert=vrfEvalCertified(seed,tpraosCanBeLeaderSignKeyVRFb)
  File "leaderLogs.py", line 107, in vrfEvalCertified
    proof = create_string_buffer(libsodium.crypto_vrf_ietfdraft03_proofbytes())
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libsodium.so: undefined symbol: crypto_vrf_ietfdraft03_proofbytes
```

Libsodium was compiled from the IOHK github repository, checkout 66f017f1

**Comment by gacallea** [comment]
Hi, I use leaderlgos regularly, last time yesterday, and it works.

Did you run ldconfig against the compiled libsodium to actually use it?

**Comment by billionairepool** [comment]
Yes, but same error. I am using libsodium.so.23.1.0

**Comment by gacallea** [comment]
I don't have issues on Ubuntu 20.04. This is what I do:

- Compile:

```
git clone https://github.com/input-output-hk/libsodium
cd libsodium
git checkout 66f017f1 && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install
```

- Then scp the resulting ```libsodium.so``` to ```/usr/local/lib/``` on the pool servers

- Create a file called ```/etc/ld.so.conf.d/libsodium.conf``` and put the following text in it:

```
# custom compiled IOHK libsodium
/usr/local/lib
```

- Run ```ldconfig```

You should be good to go. Restart ```cardano-node``` so it will use this new ```libsodium.so```

Good luck.

**Comment by billionairepool** [comment]
Ok, thank you. Rebuilding solved. I needed libsodium.so.23.3.0 and for some reason I was using libsodium.so.23.1.0

**Comment by gacallea** [comment]
you are welcome. I'm glad you solved it.
